fix(pkgs): remove missing
- because I've received the most beautiful error
  error:
         … while calling the 'derivationStrict' builtin

           at /builtin/derivation.nix:9:12: (source not available)

         … while evaluating derivation 'home-manager-generation'
           whose name attribute is located at /nix/store/4ab6vrcph07w6ra79bc04fy8bbcmb9r0-source/pkgs/stdenv/generic/make-derivation.nix:331:7

         … while evaluating attribute 'buildCommand' of derivation 'home-manager-generation'

           at /nix/store/4ab6vrcph07w6ra79bc04fy8bbcmb9r0-source/pkgs/build-support/trivial-builders/default.nix:68:16:

             67|         enableParallelBuilding = true;
             68|         inherit buildCommand name;
               |                ^
             69|         passAsFile = [ "buildCommand" ]

         (stack trace truncated; use '--show-trace' to show the full trace)

         error: undefined variable 'nodejs_21'

         at /nix/store/38wyczb9yinhv84i4aj3vbhki1imbbs9-source/home.nix:27:5:

             26|     hugo
             27|     nodejs_21
               |     ^
             28|     openssl

Resolves:
Related:
Signed-off-by: Daniel Andrei Mincă <zealous_sterner.0e@icloud.com>