fix: home-manager syntax error
* while running the flake against remove VMs ie. hs-nixos-01,
mon-nixos-01; was throwing this error because these weren't importing
Home-Manager

error:
       … while calling the 'seq' builtin
         at
«github:NixOS/nixpkgs/b67c7a60c3732edd4b947a7df8af06215851a614?narHash=sha256-JOaadoI/IC9qEvwlnjwAhwdcWkCDqEeOJ%2BcOtUH/8RQ%3D»/lib/modules.nix:402:18:
          401|         options = checked options;
          402|         config = checked (removeAttrs config [ "_module"
]);
             |                  ^
          403|         _module = checked (config._module);

       … while calling the 'throw' builtin
         at
«github:NixOS/nixpkgs/b67c7a60c3732edd4b947a7df8af06215851a614?narHash=sha256-JOaadoI/IC9qEvwlnjwAhwdcWkCDqEeOJ%2BcOtUH/8RQ%3D»/lib/modules.nix:374:13:
          373|           else
          374|             throw baseMsg
             |             ^
          375|         else

       error: The option `home-manager' does not exist. Definition
values:
       - In
`/nix/store/r5ybr0vlggrg0rxqsmyqc7d71syd033y-source/modules/cinnamon':
           {
             _type = "if";
             condition = false;
             content = {
               users = {
           ...

       Did you mean `homelab', `image' or `powerManagement'?

fix: home-manager syntax error

* while running the flake against remove VMs ie. hs-nixos-01,
mon-nixos-01; was throwing this error because these weren't importing
Home-Manager

error:
       … while calling the 'seq' builtin
         at
«github:NixOS/nixpkgs/b67c7a60c3732edd4b947a7df8af06215851a614?narHash=sha256-JOaadoI/IC9qEvwlnjwAhwdcWkCDqEeOJ%2BcOtUH/8RQ%3D»/lib/modules.nix:402:18:
          401|         options = checked options;
          402|         config = checked (removeAttrs config [ "_module"
]);
             |                  ^
          403|         _module = checked (config._module);

       … while calling the 'throw' builtin
         at
«github:NixOS/nixpkgs/b67c7a60c3732edd4b947a7df8af06215851a614?narHash=sha256-JOaadoI/IC9qEvwlnjwAhwdcWkCDqEeOJ%2BcOtUH/8RQ%3D»/lib/modules.nix:374:13:
          373|           else
          374|             throw baseMsg
             |             ^
          375|         else

       error: The option `home-manager' does not exist. Definition
values:
       - In
`/nix/store/r5ybr0vlggrg0rxqsmyqc7d71syd033y-source/modules/cinnamon':
           {
             _type = "if";
             condition = false;
             content = {
               users = {
           ...

       Did you mean `homelab', `image' or `powerManagement'?