Revert "feat(mc02:pkgs): install krr"
This reverts commit d769ce8404fb32b97b761b20431f4206ce08069e.

* the package is broken, as per
error:
       … while calling the 'derivationStrict' builtin

         at /builtin/derivation.nix:9:12: (source not available)

       … while evaluating derivation 'home-manager-generation'
         whose name attribute is located at /nix/store/kr5gpvypsqk6h2ahjk7lj40293fyzjbx-source/pkgs/stdenv/generic/make-derivation.nix:334:7

       … while evaluating attribute 'buildCommand' of derivation 'home-manager-generation'

         at /nix/store/kr5gpvypsqk6h2ahjk7lj40293fyzjbx-source/pkgs/build-support/trivial-builders/default.nix:68:16:

           67|         enableParallelBuilding = true;
           68|         inherit buildCommand name;
             |                ^
           69|         passAsFile = [ "buildCommand" ]

       (stack trace truncated; use '--show-trace' to show the full trace)

       error: Package ‘python3.12-prometrix-0.1.18-unstable-2024-04-30’ in /nix/store/kr5gpvypsqk6h2ahjk7lj40293fyzjbx-source/pkgs/development/python-modules/prometrix/default.nix:57 is marked as broken, refusing to evaluate.

       a) To temporarily allow broken packages, you can use an environment variable
          for a single invocation of the nix tools.

            $ export NIXPKGS_ALLOW_BROKEN=1

          Note: When using `nix shell`, `nix build`, `nix develop`, etc with a flake,
                then pass `--impure` in order to allow use of environment variables.

       b) For `nixos-rebuild` you can set
         { nixpkgs.config.allowBroken = true; }
       in configuration.nix to override this.

       c) For `nix-env`, `nix-build`, `nix-shell` or any other Nix command you can add
         { allowBroken = true; }
       to ~/.config/nixpkgs/config.nix.

Related: NixOS/nixpkgs#327629