fix(flake): format and conditional for user selection
* running the flake previously was complaining that
  Error: USER is set to "mida4001" but we expect "dminca"
* as a result, adjust the logic by introducing a boolean for selecting
  the correct user on the workstation
* format the code according to Nix standards

Resolves:
Related:
Signed-off-by: Daniel-Andrei Minca <zealous_sterner.0e@icloud.com>