feat(nix): implement overlays
* setup repo structure
* configure overlay for 'kluctl' package first; once this works, MVP
  delivered
* since this is the initial commit on this feature, it's obviously
  broken and throwing the following error

```sh
error:
       … while evaluating a branch condition

         at /nix/store/7gmkl9bfx98djaamhym69wkj4r3sh1q6-source/lib/lists.nix:125:9:

          124|       fold' = n:
          125|         if n == len
             |         ^
          126|         then nul

       … while calling the 'length' builtin

         at /nix/store/7gmkl9bfx98djaamhym69wkj4r3sh1q6-source/lib/lists.nix:123:13:

          122|     let
          123|       len = length list;
             |             ^
          124|       fold' = n:

       (stack trace truncated; use '--show-trace' to show the full trace)

       error: function 'anonymous lambda' called without required argument 'pkgs'

       at /nix/store/2cv47br877dpnc9p1cv3x95a27nsidb0-source/overlays/kluctl/default.nix:1:1:

            1| { pkgs, config, lib, ... }:
             | ^
            2|
```

Resolves: #9
Related:
Signed-off-by: Daniel-Andrei Minca <zealous_sterner.0e@icloud.com>