fix: signature issues while copying closure
copying path
'/nix/store/p3si6cyrp29izdv3yp93qshp4imj8kpf-unit-fluent-bit.service' to
'ssh-ng://admin@rp-nixos-01.home.arpa'...
copying path '/nix/store/zwx5w3dl6yqhral0nw4zhy8jxz52w6vs-system-units'
to 'ssh-ng://admin@rp-nixos-01.home.arpa'...  copying path
'/nix/store/01svha032w0i7qm9pa9891x0azlyk565-etc' to
'ssh-ng://admin@rp-nixos-01.home.arpa'...           copying path
'/nix/store/s0sajnfxsfq6zigmm5ix92rxqbi74zs4-nixos-system-rp-nixos-01-26.05.20260909.6aefcda'
to 'ssh-ng://admin@rp-nixos-01.home.arpa'...
error: cannot add path
'/nix/store/sqch1066kjqqdap7vv2g4la5gnic7rrp-Caddyfile-formatted'
because it lacks a signature by a trusted key
ERROR Failed to copy closure to remote host
'admin@rp-nixos-01.home.arpa' (nh/crates/nh-remote/src/copy.rs:266)
Error:
   0: Failed to copy configuration to target host
   1: nix copy --to 'admin@rp-nixos-01.home.arpa' failed (exit status:
ExitStatus(Exited(1)))
      stderr:
      copying 9 paths...
      copying path
'/nix/store/sqch1066kjqqdap7vv2g4la5gnic7rrp-Caddyfile-formatted' to
'ssh-ng://admin@rp-nixos-01.home.arpa'...
      copying path
'/nix/store/5jc28m80p5lsck3hjrii8nmkkg3kcppb-unit-oauth2-proxy.service'
to 'ssh-ng://admin@rp-nixos-01.home.arpa'...
      copying path
'/nix/store/4xap64m02c76c2yn51hvi5s18kna6j34-X-Reload-Triggers-caddy' to
'ssh-ng://admin@rp-nixos-01.home.arpa'...
      copying path
'/nix/store/da6g3qzaf1wyjn9yazflqjqpy50czbg9-unit-caddy.service' to
'ssh-ng://admin@rp-nixos-01.home.arpa'...
      copying path
'/nix/store/hych2g3n3y7d862q20mad5dvnq921c0n-fluent-bit.yaml' to
'ssh-ng://admin@rp-nixos-01.home.arpa'...
      copying path
'/nix/store/p3si6cyrp29izdv3yp93qshp4imj8kpf-unit-fluent-bit.service' to
'ssh-ng://admin@rp-nixos-01.home.arpa'...
      copying path
'/nix/store/zwx5w3dl6yqhral0nw4zhy8jxz52w6vs-system-units' to
'ssh-ng://admin@rp-nixos-01.home.arpa'...
      copying path '/nix/store/01svha032w0i7qm9pa9891x0azlyk565-etc' to
'ssh-ng://admin@rp-nixos-01.home.arpa'...
      copying path
'/nix/store/s0sajnfxsfq6zigmm5ix92rxqbi74zs4-nixos-system-rp-nixos-01-26.05.20260909.6aefcda'
to 'ssh-ng://admin@rp-nixos-01.home.arpa'...
      error: cannot add path
'/nix/store/sqch1066kjqqdap7vv2g4la5gnic7rrp-Caddyfile-formatted'
because it lacks a signature by a trusted key

Location:
   crates/nh-remote/src/copy.rs:267
error: recipe `_deploy-nixos` failed on line 25 with exit code 1