fix: overlay is used
* even though the overlay is now used and compiled, hitting an infinite
  hashing mismatch issue
    error: hash mismatch in fixed-output derivation '/nix/store/gsdgyx2wdlqlxl555n532vgyn5j5bkhb-kluctl-2.25.1-go-modules.drv':
             specified: sha256-TckT39wQn4dclcYSfxootv1Lw5+iYxY6/wwdUc1+Z6s=
                got:    sha256-iE4fPRq2kalP53AO3YaaqbRMH4Cl6XB5UseJmepoW+4=
    [0/9 built (1 failed), 0.0 MiB DL] building kluctl-2.25.1-go-modules (installPhase): Running phase: installPhase^Z
    error: 1 dependencies of derivation '/nix/store/4x4nz1a1ik137jpmcjaqi1yc9yzpiw6g-kluctl-2.25.1.drv' failed to build
    error: 1 dependencies of derivation '/nix/store/h8yslr3m7vw83z2hsyadxwb380rbm5bc-home-manager-applications.drv' failed to build
    error: 1 dependencies of derivation '/nix/store/p011vblrj14f7qhbdx496d9mak4pdg4s-home-manager-fonts.drv' failed to build
    error: 1 dependencies of derivation '/nix/store/vvwrs9c678wwnypvkzjfxspv1nalmgdc-home-manager-path.drv' failed to build
    error: 1 dependencies of derivation '/nix/store/wc39y38f1pcbz571hp2bp980frf0w7g4-home-manager-generation.drv' failed to build

Resolves:
Related:
Signed-off-by: Daniel-Andrei Minca <zealous_sterner.0e@icloud.com>