fix(caddy): lxc boot issues
* was complaining that it needs a boot drive

updating GRUB 2 menu...
installing the GRUB 2 boot loader on /dev/sda...
Installing for i386-pc platform.
/nix/store/fxvw2iil27p6km07n5mwk38vs4phc7wq-grub-2.12/sbin/grub-install:
error: failed to get canonical path of `rpool/data/subvol-104-disk-0'.
/nix/store/0ki6fqk5id55mxa1z4gsgay1q4xjnmi0-install-grub.pl:
installation of GRUB on /dev/sda failed: No such file or directory
Failed to install bootloader

* complaining about starting kernel-debug mount
restarting sysinit-reactivation.target
× sys-kernel-debug.mount - Kernel Debug File System
     Loaded: loaded (/etc/systemd/system/sys-kernel-debug.mount;
enabled; preset: ignored)
     Active: failed (Result: exit-code) since Fri 2026-05-08 23:34:20
UTC; 254ms ago
 Invocation: 807379d981c44094a282d9ffc8eb0a6e
      Where: /sys/kernel/debug
       What: debugfs
       Docs: https://docs.kernel.org/filesystems/debugfs.html
             https://systemd.io/API_FILE_SYSTEMS
         IO: 0B read, 0B written
   Mem peak: 1.7M
        CPU: 2ms

May 08 23:34:20 rp-nixos-01 systemd[1]: Mounting Kernel Debug File
System...
May 08 23:34:20 rp-nixos-01 mount[8309]: mount: /sys/kernel/debug:
permission denied.
May 08 23:34:20 rp-nixos-01 mount[8309]:        dmesg(1) may have more
information after failed mount system call.
May 08 23:34:20 rp-nixos-01 systemd[1]: sys-kernel-debug.mount: Mount
process exited, code=exited, status=32/n/a
May 08 23:34:20 rp-nixos-01 systemd[1]: sys-kernel-debug.mount: Failed
with result 'exit-code'.
May 08 23:34:20 rp-nixos-01 systemd[1]: Failed to mount Kernel Debug
File System.
warning: the following units failed: sys-kernel-debug.mount