fix: remove broken 'direnv' package
- the following compilation error was thrown

direnv> building
'/nix/store/6502yavrjbrpi7drfyhb03dslmx7zvwj-direnv-2.37.1.drv'
direnv> Running phase: unpackPhase
direnv> unpacking source archive
/nix/store/p8ywg6cpcln89lfcd8msn7sqvsajzy60-source
direnv> source root is source
direnv> Running phase: patchPhase
direnv> Running phase: updateAutotoolsGnuConfigScriptsPhase
direnv> Running phase: configurePhase
direnv> Running phase: buildPhase
direnv> go build -ldflags '-linkmode=external -X
main.bashPath=/nix/store/my9bsdsfxcaxkb400i4xvvh1ahb8pybs-bash-interactive-5.3p9/bin/bash'
-o direnv
direnv> -linkmode=external requires external (cgo) linking, but cgo is
not enabled
direnv> make: *** [GNUmakefile:68: direnv] Error 1
error: builder for
'/nix/store/6502yavrjbrpi7drfyhb03dslmx7zvwj-direnv-2.37.1.drv' failed
with exit code 2;
       last 10 log lines:
       > Running phase: unpackPhase
       > unpacking source archive
/nix/store/p8ywg6cpcln89lfcd8msn7sqvsajzy60-source
       > source root is source
       > Running phase: patchPhase
       > Running phase: updateAutotoolsGnuConfigScriptsPhase
       > Running phase: configurePhase
       > Running phase: buildPhase
       > go build -ldflags '-linkmode=external -X
main.bashPath=/nix/store/my9bsdsfxcaxkb400i4xvvh1ahb8pybs-bash-interactive-5.3p9/bin/bash'
-o direnv
       > -linkmode=external requires external (cgo) linking, but cgo is
not enabled
       > make: *** [GNUmakefile:68: direnv] Error 1
       For full logs, run:
         nix log
/nix/store/6502yavrjbrpi7drfyhb03dslmx7zvwj-direnv-2.37.1.drv
error: 1 dependencies of derivation
'/nix/store/1wm3yc1h0aazdk2dkjhw6yqsn5hfxlrd-hm_..zshrc.drv' failed to
build
error: 1 dependencies of derivation
'/nix/store/nl04xbl33m39j656wkr7cj6gyfq4dn4z-home-manager-fonts.drv'
failed to build
error: 1 dependencies of derivation
'/nix/store/8damy2gr61x07azvyp2aw3vgxmlkp24k-home-manager-path.drv'
failed to build
error: 1 dependencies of derivation
'/nix/store/w59pfsr2sq20l2q15av677p9nly8p64g-home-manager-generation.drv'
failed to build
┏━ 1 Errors:
┃ error: builder for
'/nix/store/6502yavrjbrpi7drfyhb03dslmx7zvwj-direnv-2.37.1.drv' failed
with exit code 2;